#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:18

pipelines:
  default:
    - parallel:
      - step:
        name: Deploy to Cloudflare Pages
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npx wrangler pages deploy build --project-name=docusaurus-loops-and-logic --branch=development
          
  tags:
    "*":
    - step:
      name: Deploy to Cloudflare Pages
      caches:
        - node
      script:
        - npm install
        - npm run build
        - npx wrangler pages deploy build --project-name=docusaurus-loops-and-logic --branch=main
